// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainSolution_ServerApp.Models.Data;

#nullable disable

namespace TrainSolution_ServerApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250524144431_TrainComponentSolution")]
    partial class TrainComponentSolution
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("TrainSolution_ServerApp.Models.TrainComponents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InstallDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Components", (string)null);
                });

            modelBuilder.Entity("TrainSolution_ServerApp.Models.Trains", b =>
                {
                    b.Property<string>("VehicleNumber")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEndsService")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateIntoService")
                        .HasColumnType("TEXT");

                    b.Property<string>("FleetName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("VehicleNumber");

                    b.ToTable("Trains");
                });
#pragma warning restore 612, 618
        }
    }
}
