// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainSolution_ServerApp.Models.Data;

#nullable disable

namespace TrainSolution_ServerApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("TrainSolution_ServerApp.Models.TrainComponents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InstallDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Components", (string)null);
                });

            modelBuilder.Entity("TrainSolution_ServerApp.Models.Trains", b =>
                {
                    b.Property<string>("VehicleNumber")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEndsService")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateIntoService")
                        .HasColumnType("TEXT");

                    b.Property<string>("FleetName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("VehicleNumber");

                    b.ToTable("Trains");

                    b.HasData(
                        new
                        {
                            VehicleNumber = "VH001",
                            DateEndsService = new DateTime(2030, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateIntoService = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FleetName = "Fleet A"
                        },
                        new
                        {
                            VehicleNumber = "VH002",
                            DateEndsService = new DateTime(2031, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateIntoService = new DateTime(2000, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FleetName = "Fleet A"
                        },
                        new
                        {
                            VehicleNumber = "VH003",
                            DateEndsService = new DateTime(2050, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateIntoService = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FleetName = "Fleet B"
                        },
                        new
                        {
                            VehicleNumber = "VH004",
                            DateEndsService = new DateTime(2050, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateIntoService = new DateTime(2020, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FleetName = "Fleet B"
                        },
                        new
                        {
                            VehicleNumber = "VH005",
                            DateEndsService = new DateTime(2031, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateIntoService = new DateTime(2018, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FleetName = "Fleet C"
                        },
                        new
                        {
                            VehicleNumber = "VH006",
                            DateEndsService = new DateTime(2031, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateIntoService = new DateTime(2018, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FleetName = "Fleet C"
                        },
                        new
                        {
                            VehicleNumber = "VH007",
                            DateEndsService = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateIntoService = new DateTime(1994, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FleetName = "Fleet D"
                        },
                        new
                        {
                            VehicleNumber = "VH008",
                            DateEndsService = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateIntoService = new DateTime(1994, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FleetName = "Fleet D"
                        },
                        new
                        {
                            VehicleNumber = "VH009",
                            DateEndsService = new DateTime(2030, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateIntoService = new DateTime(2000, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FleetName = "Fleet A"
                        },
                        new
                        {
                            VehicleNumber = "VH010",
                            DateEndsService = new DateTime(2050, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateIntoService = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FleetName = "Fleet B"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
